---
- set_fact:
    namespace_clause: ""
  when: ar_os_secret_link_namespace is not defined or ar_os_secret_link_namespace is none

- set_fact:
    namespace_clause: "-n {{ ar_os_secret_link_namespace }}"
  when: ar_os_secret_link_namespace is defined and ar_os_secret_link_namespace is not none

- name: Link Secret with Service account
  command: oc secret link {{ ar_os_secret_link_item.name }} {{ ar_os_secret_link_item_secret }} --for=pull {{ namespace_clause }}
  with_items: "{{ ar_os_secret_link_item.link_secrets }}"
  when: ar_os_secret_link_item.link_secrets is defined
  loop_control:
    loop_var: ar_os_secret_link_item_secret
