---
# Each record in this loop represents secrets to link with a (parent object) service account
- name: Link Secret with Service account
  include_tasks: oc_secret_link.yml
  with_items: "{{ ar_os_secret_link_item.link_secrets }}"
  when: ar_os_secret_link_item.link_secrets is defined
  loop_control:
    loop_var: ar_os_secret_link_item_secret
