---
# Each record in this loop represents a service account and list of secrets to use
- name: Link Secrets with Service accounts
  include_tasks: link_secret.yml
  with_items: "{{ ar_os_secret_link_items }}"
  loop_control:
    loop_var: ar_os_secret_link_item
