---
- name: Check if secret link already exists
  command: oc get sa {{ ar_os_secret_link_item.sa_name }} -n {{ ar_os_secret_link_namespace }} -o jsonpath='{.imagePullSecrets[*].name}'
  register: sa_stat
  changed_when: false
  failed_when: false

- set_fact:
    _ar_os_secret_link_namespace_clause: ""
  when: ar_os_secret_link_namespace is not defined or ar_os_secret_link_namespace is none

- set_fact:
    _ar_os_secret_link_namespace_clause: "-n {{ ar_os_secret_link_namespace }}"
  when: ar_os_secret_link_namespace is defined and ar_os_secret_link_namespace is not none

- name: Set Fact Operation pull
  set_fact:
    _ar_os_secret_link_docker_operation: 'pull'
  when: ar_os_secret_link_item_secret.operation is not defined or ar_os_secret_link_item_secret.operation != 'push'

- name: Set Fact Operation push
  set_fact:
    _ar_os_secret_link_docker_operation: 'pull,mount'
  when: ar_os_secret_link_item_secret.operation is defined and ar_os_secret_link_item_secret.operation == 'push'

- debug: var=ar_os_secret_link_item
- debug: var=ar_os_secret_link_item_secret

- name: Link a single secret with a service account
  command: oc secret link {{ ar_os_secret_link_item.sa_name }} {{ ar_os_secret_link_item_secret.secret_name }} \
             --for={{ _ar_os_secret_link_docker_operation }} {{ _ar_os_secret_link_namespace_clause }}
  when: ar_os_secret_link_item_secret.secret_name not in sa_stat.stdout_lines[0].split(' ')